{{- if gt (len .Values.moodlecronjob.jobs) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-{{ include "moodlecronjob.job_name" . }}
  namespace: {{ .Release.Namespace }}
data:
  cronjob-script: |-
{{ tpl ( .Files.Get "scripts/cronjob.sh" ) . | nindent 4 }}
{{- end }}