{{- if and .Values.dbpMoodle.networkPolicies.enabled .Values.redis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-internal-ingress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 6379
    {{- with .Values.dbpMoodle.networkPolicies.monitoringNamespaceLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9121
    {{- end }}
{{- end }}
