# https://github.com/terraform-docs/gh-actions

name: Generate Helm-Docs on Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/**'
      - '.github/templates/**'

jobs:
  create_helm-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checking out code to Runner
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  #v6.0.3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Generate Helm-Docs
      uses: hpi-schul-cloud/infra-tools/.github/actions/helm-docs@tf-helm-docs-v1
      with:
        # provide name of dirs to run helm-docs on, separate by comma without space
        src_path: "charts"
        template_file: ".github/templates/README.md.gotmpl"
        # provide name of dirs to ignore, separate by comma without space
        ignored_dirs: charts/dbp-moodle/charts/cronjob,charts/dbp-moodle/charts/etherpad
        git_push: true
        username: "devops"
        email: "devops@dbildungsplattform.de"