---
name: Docker Image Trivy Image Vulnerability Scan Cron Job
on:
  schedule:

    - cron: '0 2 * * *'
  workflow_dispatch:
permissions:
  # security-events required for all workflows; action, contents only required for workflows in private repositories
  security-events: write
  actions: read
  contents: write
jobs:
  trivy_image_scan_cron:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/trivy-scan.yaml@main
    with:
      image-ref: 'ghcr.io/dbildungsplattform/moodle:latest'
  clamav_scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-image-clamav.yaml@7
    with:
      image_ref: 'ghcr.io/dbildungsplattform/moodle:latest'
